### PR TITLE
MSVC2015 patches and updates to various libs

### PR DESCRIPTION
**Pull request by boberfly**
Hi John,

This is quite a big PR but perhaps just some cherry-picks could be done (or the whole lot would be great if it builds on Linux/macOS I don't mind!)

The libs added/updated in here are:
libtiff to v4.0.8 - Could be dangerous, but MSVC2015 wouldn't build the older one properly
GLEW 2.1.0 - For CMake support on Windows, simplifies things
Xerces-C 3.2.0 - Looks like Appleseed already updated, and it has a CMake script now
zlib-1.2.11 - Windows doesn't come with it, can be ignored on Linux/macOS

Modifications:
python 2.7.11 - added a CMake build system, and patched some problematic MSVC2015 fixes in, and exporting a few symbols that Gaffer is after, I guess stuff that's not normally in the public-facing API
OpenSSL - CMake support
TBB - CMake support
Appleseed - Fixes to allow dynamic-linked external libs
HDF5 - Small compile fix for MSVC2015
OSL - Flex/Bison pathing fixes in CMake, as well as LLVM 3.4 linking to the right static libs .lib not .a

Added a winbuild/ directory with .bat files that mimic the .sh scripts in build/ as well as flex/bison (also comes with Qt so maybe we can use that one provided instead). The added CMake stuff is just Windows for now but maybe Linux/macOS might benefit as well.

Currently I build my custom CMake+MSVC Cortex outside of this tree so that isn't included in this PR. OpenVDB doesn't compile yet but maybe we can update to v4 soon and try again, v4 it wasn't building with MSVC2013 but it should be ok with 2015, and I have cblosc already ready to go in another branch for its dependency.

### CODE REVIEW

**Comment by boberfly** [comment]
Cortex feels like I'm back to square one going from MSVC 2013 to 2015, just tested an older version before the refactors and get linker errors with those exports (they exist though when I use a dumpbin /exports >> dump.txt), very strange. Still builds on 2013.

**Comment by boberfly** [comment]
I came up with something similar here:
https://github.com/PixarAnimationStudios/USD/blob/master/pxr/base/lib/tf/refPtr.h#L1304

Just base classes don't work with this, so I'm currently stuck on stuff like ChannelOp, hmm....

**Comment by johnhaddon** [comment]
Question : What are the chances of getting the regular `build/*` scripts to work on Windows? My concern is that two sets of scripts will naturally diverge (I have no means of testing a Windows-specific script), so would prefer one set of scripts if possible. Could we use the Linux subsystem thingo to run the bash scripts perhaps?

**Comment by boberfly** [comment]
Hmm good question about the bash scripts using the Linux subsystem, I haven't dared to try. My guess is it'll fail as that subsystem is really for running Linux binaries and there's no MSVC there...

- Just a heads-up I'm looking into refactoring the dependency stuff on my end right now, so this PR can be ignored really, plus I'm preparing for a world of archives and diff patches that I'm guessing you'll do to all the remaining ones? I'll start by PR'ing GLEW-2.1.0 as I need CMake in it.

**Comment by boberfly** [comment]
Having another thought about this, what's your opinion on going with a python script to build dependencies instead of bash/shell scripts? Much like how USD approaches it eg. 
https://github.com/PixarAnimationStudios/USD/blob/master/build_scripts/build_usd.py

**Comment by johnhaddon** [comment]
> what's your opinion on going with a python script to build dependencies instead of bash/shell scripts?

If it lets you do Windows builds without using a divergent set of scripts, I would be up for it. If we were using Python I'd probably also refactor things quite a bit, maybe even to the point where there was just a simple config file per dependency and one generic build script. If we abandon the lo-fi bash approach, there's certainly no reason to have every dependency repeat the exact same "make a working dir, unpack the archive" bit...

**Comment by boberfly** [comment]
Hmm, awhile ago I was looking into something called fips for something like this, but it really just wraps cmake projects (although I have been making most of dependencies all use the cmake option where possible in my windows dependency branch):
https://github.com/floooh/fips

And started a thread about also supporting SCons:
https://github.com/floooh/fips/issues/124

Maybe that's a bit too much over just a more simplified python script that we could just dev up that's data-driven like you said.

**Comment by johnhaddon** [comment]
Thanks for the links - fips looks pretty interesting. Like you say though, I suspect we could knock up something simpler that just addresses our exact requirements and nothing more. Just so you know where I'm at in terms of time to spend on this, it is absolutely my intention to get Cortex/Gaffer to the point where they build on Windows out of the box, and to do that in a timely fashion. But for the dependencies project I think it's more realistic that it'll be a slow move towards something python-based, and you'll be flying solo for a little while still. Still, please do keep making the more focussed PRs like your GLEW one - that's the kind of stuff I can test and merge relatively quickly.

**Comment by boberfly** [comment]
Alright good to know, I'll focus more on upgrading my old dependency branch for now so I can get the latest cortex/gaffer to build again and have this refactor be something I do in the background. I'll look into testing these archived changes on linux like with GLEW somehow too. Cheers!

**Comment by hypotheticalinc** [comment]
I'm up for testing the builds on Linux as the dependencies get refactored. I'm very interested in being able to build cross platform because my render farm runs Linux and workstations are Windows. (A longer-term goal is having Gaffer run from within DCC apps like 3ds Max so I'd ideally have the ability to build against compiler versions as needed to ensure compatibility.)

**Comment by boberfly** [comment]
I just joined this google group about the vfx platform wanting to maintain their own dependency builds, possibly with rez+cmake which might make our lives easier:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vfx-platform-discuss/1g0pt4hhjqg/gngSFlD6BgAJ
Would be nice if everyone in the industry just makes a CI system for these that everyone can agree upon and share...

**Comment by johnhaddon** [comment]
Closing this, since we're moving towards config-based builds for all platforms.

**Pull request closed without merging**
