### PR TITLE
VDB : Update to OpenVDB 4.0.2

### PR DESCRIPTION
**Pull request by donboie**
This matches VFX platform 2017 version of 4.x.

I've not included the maya or houdini plugins as they don't seem to be referenced in the build script. Also do we need more of an audit trail for where the files came from? 

http://www.openvdb.org/download/openvdb_4_0_2_library.zip

Perhaps we can keep the original downloads using git LFS in the future?

### CODE REVIEW

**Comment by boberfly** [comment]
Hey Don,

Did you also add c-blosc? I found that it was needed for OpenVDB, I have it here but it's pretty much just an add with a cmake build script:
https://github.com/boberfly/gafferDependencies/tree/windows/c-blosc-1.11.2

Maybe instead of git-LFS, how about git submodules and/or use CMake's add_dependency feature? The only issue is that some of these libs have additional custom patches to make them build that don't exist from the original source, Appleseed just make one big deps repo as well like this one with custom patches as well.

**Comment by johnhaddon** [comment]
Great - thanks Don.

> Do we need more of an audit trail for where the files came from? 

Yep, an audit trail would be good.

> Perhaps we can keep the original downloads using git LFS in the future?

I do wonder if the "just keep all the files in one repo" approach is becoming too cumbersome to continue with much longer anyway. The sheer number of files and the weight of all the history is making git pretty slow.

Really I'm hoping that VFXPlatform will start providing packages we can use directly, but I suspect that's too optimistic, and there are packages we use that are outside the platform anyway. The alternative would be to download the source packages as part of the build, and patch them on the go, maintaining some sort of local cache to avoid downloading all the time. I seem to recall you had something like that already? Any thoughts on the pros/cons of each approach?

**Comment by donboie** [comment]
The problem with my just in time download approach is it all fails when the download URLs change - this doesn't happen too often (especially if you have a local cache) but it makes the process unreliable and you have to go hunting down new download paths on occasion.

I propose we a copy of the 3rd party software release archive and store them in git LFS ( or some other system) and patch just prior to build. I think we should be able store archives of all versions of libraries and which to use at build time.

Perhaps an option to additionally to directly use the download path might allow us to perform continuous integration on 3rd party libraries & gaffer?

**Comment by johnhaddon** [comment]
> I propose we a copy of the 3rd party software release archive and store them in git LFS ( or some other system) and patch just prior to build. I think we should be able store archives of all versions of libraries and which to use at build time.

OK, sounds reasonable. Shall we prototype this with a single project next time we come to update one then? Assuming we have time of course...

> Perhaps an option to additionally to directly use the download path might allow us to perform continuous integration on 3rd party libraries & gaffer?

I'm a little wary of that because I'm trying to use the dependencies project to define a _single_ recipe that we recommend and support for building Gaffer. We also have fairly limited resources in terms of CI time on Travis, and building more permutations could quickly get out of hand.

I think there's value in what you suggest, but probably more so in a studio scenario where more esoteric deployments into different hosts (Maya etc) are required. In that scenario, I'd expect the dependencies to be driven more by the host and the particular studio setup than anything in this repo...

**Comment by donboie** [comment]
> I'm a little wary of that because I'm trying to use the dependencies project to define a single recipe that we recommend and support for building Gaffer. We also have fairly limited resources in terms of CI time on Travis, and building more permutations could quickly get out of hand.
> 
> I think there's value in what you suggest, but probably more so in a studio scenario where more esoteric deployments into different hosts (Maya etc) are required. In that scenario, I'd expect the dependencies to be driven more by the host and the particular studio setup than anything in this repo...

Agreed it's not something we'd run on travis but it might be nice additional extra in some cases in studios or for some developers mucking around with the dependencies.

**Comment by donboie** [comment]
I was going to add blosc as per @boberfly's suggestion. 

Perhaps blosc is only required for reading real world vdb files? If it's required I'll try adding the archive and updating the build script to unzip & build as discussed.

**Comment by johnhaddon** [comment]
Sounds good.

**Pull request merged**
