### PR TITLE
Update Cycles to 4.2.0

### PR DESCRIPTION
**Pull request by boberfly**
The blender guys made a 4.2 release in the last few days. I'll look into Gaffer changes soon.

### CODE REVIEW

**Comment by boberfly** [comment]
Just to note, zstd's cmake config is directly copied from:
https://projects.blender.org/blender/blender/src/commit/1b7485f20892523942752f81239807b2eab0f00b/build_files/build_environment/cmake/zstd.cmake#L5

**Comment by murraystevenson** [comment]
Thanks Alex! It will be great to get the Cycles 4.2 update in for Gaffer 1.5.

I've actually run into some of this already with a local branch using Cycles 4.1.1, which I also updated to 4.2.0 last night. 

My workaround for the change to how precompiled dependencies are handled is a bit simpler (I'm just removing those stub directories under ./lib/), which I think we'd prefer here, but your `precompiledLibsToggle.patch` looks like it would be beneficial to get back into Cycles itself for the long run if you think that's something they'd accept?

I also found that the linked zstd cmake config was a bit overly verbose for my taste, where it was restating a lot of the defaults, so mine is attempting to be a fair bit simpler.

My branch is also aiming to include OIDN with CUDA support. I'll try to put it up later today and maybe we can go with it instead?

**Comment by boberfly** [comment]
> your precompiledLibsToggle.patch looks like it would be beneficial to get back into Cycles itself for the long run if you think that's something they'd accept?

Yep got it here, deleting the directiries was getting in the way at the git level but the tarball wouldn't have that issue you're right.
https://projects.blender.org/blender/cycles/pulls/13

> My branch is also aiming to include OIDN with CUDA support. I'll try to put it up later today and maybe we can go with it instead?

Cool, yeah I got OIDN also here but left it out to keep things simpler but that would be good to include too.

I just remembered too, could we also get Meson support in the docker builder? For Epoxy so the USD support can be added back in. I have a patch to fix up their python detection for that somewhere here that I'd like to upstream also.

Cheers

**Comment by murraystevenson** [comment]
Closing in favour of the Cycles 4.2 update in #267

**Pull request closed without merging**
