### PR TITLE
EXR : Update to new build system (same version 2.2.0)

### PR DESCRIPTION
**Pull request by boberfly**
IlmBase/PyIlmBase are in the same build config, also using CMake. Tested on Linux.

### CODE REVIEW

**Comment by johnhaddon** [comment]
Could you rename the EXR directory to OpenEXR? The directory name is used as the name of the project in Gaffer's official list of dependencies (in the info window and `gaffer license`), so we need to use the full name.

**Comment by johnhaddon** [comment]
Yep - that's great thanks.

**Comment by boberfly** [comment]
Great, the commit should have all those changes now.

**Comment by johnhaddon** [comment]
Thanks! Just so you know, I'm going to leave these PRs sitting until I find the time to do a full build/test on both Linux and OSX. Shouldn't be long now since I need to do a Cortex update, but I'd rather not merge until I'm able to build myself from scratch. My past experience is that even minor tweaks to this setup can bring the whole house of cards tumbling down...

**Comment by johnhaddon** [comment]
Closing this in favour of the smaller changes I made in #130. I've previously run into trouble using the CMake build of OpenEXR rather than the autoconf one, so I've stuck with autoconf for now. I see they've been putting a lot of work into OpenEXR for an upcoming release, so happy to revisit once that is out.

**Pull request closed without merging**
