### PR TITLE
Qt5 : include cmake files in package

### PR DESCRIPTION
**Pull request by dboogert**
Copies the files from the Qt installation required to build with Gaffer with CMake.

### CODE REVIEW

**Comment by dboogert** [comment]
I should mention this allows  @boberfly gaffer cmake script to find gaffer dependencies version of Qt5.

**Comment by boberfly** [comment]
It sure does, on the Windows side I'm packaging this via 7zip.

**Comment by johnhaddon** [comment]
Ugh. Qt wants to put this dirty great mkspecs nonsense right in the middle of the package I'm trying to keep nice and clean?

**Comment by johnhaddon** [comment]
> I can update the Qt build to target a subdir to keep this clean but we'll probably have to change a bunch of other stuff which might be more onerous.

Yeah, I don't want to make life too hard. I just wanted to prod you to check that this really is necessary and that alternatives have been considered.

> The CMake FindQt didn't work without this mkspecs stuff as my first attempt just installed the cmake directory and it failed.

OK, merging...

**Pull request merged**
