### PR TITLE
GCC 11.2.1 build improvements

### PR DESCRIPTION
**Pull request by murraystevenson**
These are the changes I've needed to build the current dependencies with the new build container in https://github.com/GafferHQ/build/pull/34 along with a few adjustments to Qt in order to align the Rocky 8 builds more closely with what we currently produce from CentOS 7 and clean up a few unnecessary Qt modules.

@boberfly I've included your LibWebP and Qt contributions from #247 (thanks!), though I haven't run into the Boost or LLVM issues you mention yet, so I've left those out for the moment. Once we produce Gaffer 1.4 builds from the new container, it'd be great if you could test them out and see if you run into any issues.

The most contentious thing here might be the removal of OpenSSL. This was prompted by running into conflicts between the heavily patched system libraries and our vanilla versions - better described [here](https://github.com/conda/conda/issues/10241#issuecomment-876314011). Removing OpenSSL entirely appears to still allow usage of `ssl` in Python on distros that include a system version of OpenSSL 1.1.1, though it'll fail on distros that only provide OpenSSL 3.x.x unless they also have OpenSSL 1.1.1 installed. Rocky 9 includes OpenSSL 3.0.7 by default, but 1.1.1k can be installed via `compat-openssl11` and then Gaffer's Python seems quite happy to use it.

Another alternative could be to see if we could distribute the patched system OpenSSL libraries with the dependencies build, but it'd probably be better for us to try to avoid including such a security critical library as part of Gaffer?

### CODE REVIEW

**Comment by murraystevenson** [comment]
The OpenSSL removal might need a bit more thought when building in the Centos 7 build container as it results in Python being built without SSL support. The `ci-base` image we use in the Rocky 8 container comes with `openssl` and `openssl-devel` 1.1.1k installed, which is allowing Python to build with SSL support there...

**Comment by johnhaddon** [comment]
Can we just patch the 2.x build container to include `openssl-devel` as well?

**Comment by murraystevenson** [comment]
> Can we just patch the 2.x build container to include openssl-devel as well?

Yeah, that looks like it could be a path forward. `openssl-devel` on Centos 7 is 1.0.2, using that would allow us to be compatible with stock Centos 7, but not with more modern distros that usually ship some variant of 1.1.1. Otherwise, we go for 1.1.1 and Centos 7 users could install `openssl11` for compatible libraries. Python 3.10+ also [requires](https://peps.python.org/pep-0644/) 1.1.1, if we ever needed a build variant of old glibc with modern Python...

We can build Python with 1.1.1 on Centos 7 by installing `openssl-devel` and `openssl11-devel`, then adjusting CPPFLAGS and LDFLAGS as mentioned in the Centos 7 section [here](https://github.com/pyenv/pyenv/wiki/Common-build-problems#error-the-python-ssl-extension-was-not-compiled-missing-the-openssl-lib). `--with-openssl=` doesn't appear to help due to the headers being in `include/openssl11/openssl` rather than `include/openssl`...

Either way, I'll merge what we have here to continue with the Gaffer CI testing, and then we can follow up with any 2.x build container changes (in the same 2.x container update we could also include `sqlite-devel` to address that existing request for Python sqlite3 support).

**Comment by marcomeyerVFX** [comment]
@murraystevenson just curious why the wayland platform plugin was disabled? Were there any issues with the build or is it just to trim it down? I was just trying to run gaffer on a wayland compositor on Rocky 9 and I'm getting an error from Qt that the plugin is missing. Any chance you can get that back enabled for the prebuilt binaries in the future? 

```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/opt/gaffer/1.4.0.0b5/qt/plugins"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, webgl, xcb.

zsh: IOT instruction (core dumped)  gaffer
```

**Pull request merged**
