### PR TITLE
OpenImageIO: Suppress GIF and WEBP so it doesn't pick it from the host machine.

### PR DESCRIPTION
**Pull request by boberfly**

### CODE REVIEW

**Comment by johnhaddon** [comment]
Hey Alex, what's the background on this one? What problems was this causing? Perhaps the GIF/WEBP libraries were dynamic so we ended up with link failures at runtime?

**Comment by johnhaddon** [comment]
Nevermind, I see that our official builds never supported these anyway, so there's no harm in suppressing them explicitly. Would still be interested to know what the problem was though, in case it impacts how we might support those formats in future.

**Comment by boberfly** [comment]
Hey John, by the looks of it the ASWF dockers pre-loaded in libgif and libwebp so the OIIO build process picked them up. When I took out the final Gaffer build and ran it on Ubuntu 20.04 it was after libwebp.so.4 and libgif.so.4 but they don't quite match up with Ubuntu's lib version numbers (and we don't want to be dependent on host-specific libs anyways).

I think we are free to support them, but would need to build them as part of the dependencies chain (unless you're up for just copying them out from CentOS directly?)

**Comment by johnhaddon** [comment]
> Hey John, by the looks of it the ASWF dockers pre-loaded in libgif and libwebp so the OIIO build process picked them up. When I took out the final Gaffer build and ran it on Ubuntu 20.04 it was after libwebp.so.4 and libgif.so.4 but they don't quite match up with Ubuntu's lib version numbers (and we don't want to be dependent on host-specific libs anyways).

That makes sense - thanks for the info.

> I think we are free to support them, but would need to build them as part of the dependencies chain (unless you're up for just copying them out from CentOS directly?)

I think it'd be better to build them, so we have the same build process for MacOS and Linux (and one day Windows?). But that can wait for another day, since nobody has yet complained of a lack of GIF or WebP support...

**Pull request merged**
