### PR TITLE
Added missing dependencies for ftrack support (QtSvg, OpenSSL and QtXml) and their dependencies.

### PR DESCRIPTION
**Pull request by hdd**
We haven't been able to test these changes on OSX, but we expect to see them working.
Having support for SVG might allow you to remove the step where you compile the svg into png.

### CODE REVIEW

**Comment by johnhaddon** [comment]
Thanks for this, and sorry for the delayed response. I'll take a proper look at this (and the OSX build) when I next come to make a release, which I anticipate being fairly soon now.

**Comment by hdd** [comment]
Hi John, no worries, we are looking now on whether we can manage to add qwebkit as well, as nowadays a lot of asset management, provides html access for various things.
In any case we'll open a separate pull request for this.
Cheers.
L.

**Comment by johnhaddon** [comment]
I've got as far as determining that this certainly doesn't work on OSX. OpenSSL wants to build 32-bit by default, and when I set the random environment variable they've chosen to mean "make me a sensible 64-bit build please", I just get linking errors when building Python.

It also seems that the builds I've been making on OSX might have supported SSL all along, because it seems to be part of the system install. What's the best way to test the functionality that you need? If I can `import ssl` is that sufficient? Do you think it's 100% necessary to build and ship OpenSSL for Gaffer, or could we rely on a system install on Linux too? Can it be considered part of the furniture?

**Comment by hdd** [comment]
Hi,
I guess we can assume openSSL is available on the system.
Yes importing ssl should be enough.
We can clean up this patch , removing the ssl build and make it use the system one if available.
We just didn't want to make this assumption at this stage.

**Comment by est77** [comment]
Removed openSSL code and build scripts. Use system ssl instead.
Rebased, so that openSSL code does not appear in the history.

**Comment by johnhaddon** [comment]
Sorry for the continued delay on this - I've had problems building it both my Linux box and my Mac, and I no longer have access to a CentOS6 build machine at Image Engine. I've also concluded that I was wrong to think that using the system SSL would be OK, having just done a build with it and seen it all fail on Travis. So, I'm working on getting that working first, on both Linux and Mac.
 
Please bear with me while I chug through this - once I have a decent SSL setup I'll then take another look at your Qt changes.

**Comment by hdd** [comment]
No worries about the delays, guess you are busy with other stuffs.
Let us know if there's anything we can do to help you out on this.
Cheers.

**Comment by johnhaddon** [comment]
I've merged an OpenSSL build to master now, from #10. I've also put up an [updated binary download](https://github.com/johnhaddon/gafferDependencies/releases/tag/0.26.0.0) for Linux, built from master. If you get a chance, could you give that a shot and let me know if it works for you? Once we're all happy with that, I'll take a look at the Qt bits...

**Comment by est77** [comment]
We just tested it on linux (Centos 7) and it works.
Thanks!

**Comment by johnhaddon** [comment]
Good news!

**Comment by johnhaddon** [comment]
Closing as stale - please make a new PR for the Qt bits if necessary...

**Pull request closed without merging**
