### PR TITLE
Assorted build fixes

### PR DESCRIPTION
**Pull request by themissingcow**
- Updates some projects to support newer macOS SDK paths
- Updates `Python` to use the dependencies-build `OpenSSL`

### CODE REVIEW

**Comment by themissingcow** [comment]
Turns out https://github.com/GafferHQ/dependencies/pull/158/commits/6c2c834f3c3c47957b8022a2df627d56c44a5ebc is disastrous, as we now just have a world of `OpenGL is deprecated` errors. This is going to need some more joined up thinking. Maybe we need to just built it on `10.13`.

**Comment by johnhaddon** [comment]
> Turns out 6c2c834 is disastrous, as we now just have a world of OpenGL is deprecated errors. This is going to need some more joined up thinking. Maybe we need to just built it on 10.13.

Does setting MACOSX_DEPLOYMENT_TARGET=10.13 help at all?

**Comment by johnhaddon** [comment]
I've included 516a5e6 in https://github.com/GafferHQ/dependencies/pull/164 since it was needed there.

**Comment by themissingcow** [comment]
The salient parts of this are included in #164

**Pull request closed without merging**
