### PR TITLE
Blosc build

### PR DESCRIPTION
**Pull request by donboie**
Example of build script for blosc which upacks to a working directory & builds from there. 

I've commited the c-blosc archive directly (not using LFS) so this example will compile.

### pros

+ moves build directory out of tree
+ ensures we must separate patches from the source package
+ allows for multiple library versions to coexist in one checkout and therefore quick switching between versions

### cons

- LFS doesn't work on public forks.
- LFS requires being able to open a https connection to github-cloud.s3.amazonaws.com

### CODE REVIEW

**Comment by johnhaddon** [comment]
Dumb question - does the VDB build now pick up the Blosc library with this? I didn't see any change to the VDB build arguments, but maybe it manages to find it somehow anyway?

**Comment by donboie** [comment]
Oh I just put this up to discuss how we might change building 3rd party libraries and didn't update the vdb build to use it. I'll fix this up now.

**Comment by johnhaddon** [comment]
Hit a minor problem with this in that `realpath` doesn't exist on my Linux box or my Mac. A bit of googling seems to suggest it's maybe archaic/nonstandard? Is there a particular need to use it, or could we simply ```cd `dirname $0`/../working``` at the start, similar to what we do in the other build scripts?

**Comment by donboie** [comment]
removed the need for realpath.

**Pull request merged**
