### PR TITLE
TIFF : Update to version 4.0.9

### PR DESCRIPTION
**Pull request by boberfly**
Updating libtiff to 4.0.9 and using the new build system. Tested on Linux.

### CODE REVIEW

**Comment by boberfly** [comment]
Hoping CMAKE_PREFIX_PATH will make the build look for the built JPEG, might need to double-check that...

**Comment by johnhaddon** [comment]
Needs a rebase...

**Comment by boberfly** [comment]
Oh yeah because of the PNG PR merge? I can do this when I get home, cheers.

**Comment by boberfly** [comment]
Rebased @johnhaddon cheers!

**Comment by johnhaddon** [comment]
I've merged a [more conservative version](https://github.com/GafferHQ/dependencies/commit/06f61490b11f59eb690e15e50c4a2db1e5b426aa) of this :

- Stuck with the old version
- Didn't use CMake

We can look at the other stuff in the future when we finish the Windows push, but right now the priority needs to be getting everything over onto config-based builds without adding unnecessary changes to the forthcoming Linux/Mac releases.

**Pull request closed without merging**
