### PR TITLE
VFXPlatform 2022 updates

### PR DESCRIPTION
**Pull request by johnhaddon**
This brings us mostly up to date with VFXPlatform 2022, and also updates to the latest of several packages not included in the platform.

### CODE REVIEW

**Comment by andrewkaufman** [comment]
Was there a reason to not update OCIO?

**Comment by johnhaddon** [comment]
I have an OCIO update in progress, but it requires much more work on the Gaffer side, particularly the GPU transform in the Viewer. The plan was to have @danieldresser-ie tackle this around the same time he adds the wipes to the Viewer. In the meantime, I want to get testing with the other dependency upgrades...

**Comment by johnhaddon** [comment]
@danieldresser-ie, would be good if you could give this a quick once-over...

**Comment by danieldresser-ie** [comment]
Nothing looks off to me.

**Pull request merged**
