### PR TITLE
windows build

### PR DESCRIPTION
**Pull request by ericmehl**
Building on the hard work of @boberfly, I have sorted out what I think is a successful set of changes to the Gaffer Dependencies, Cortex and Gaffer to consider for adding compatibility for Windows.

I tried to keep it pretty organized by rebasing to clean things up. Please let me know what you think - I'm new to contributing to open source projects and very open to feedback.

### CODE REVIEW

**Comment by ericmehl** [comment]
That makes sense to me - it does seem like there are enough differences where adding endless switches based on platform might become a burden.

On a related note - I've overhauled this dependencies to split and combine commits so as you read through the history top to bottom each commit deals with only one package at a time. That should make it easier to follow along. 

It's building in a separate branch now and I'll update this PR once that's confirmed to be working.

**Comment by boberfly** [comment]
Ahh just saw this now. Yeah the second branch sounds good to me, and I guess later merge them somehow in the future, perhaps when everything is tarballed and we can decide on a unified build script, maybe with python...

Btw great stuff @ericmehl I'm glad someone continued with it, as I've been time-poor at work up until now. Cheers!

**Comment by ericmehl** [comment]
Thanks @boberfly! I've been swamped with other things the last couple weeks too but hoping to make some time to get the PRs caught up this week. I have the dependencies reorganized so now it's on to Cortex and Gaffer to put together a history that's easy to sort through.

It's ongoing (but slow) and more to come soon!

**Comment by johnhaddon** [comment]
> Do you prefer I just close this PR and reopen one with msvc2017_for_merge, or update this PR, potentially with a bunch of commits showing up that are already part of master?

A fresh PR with only the commits you want merged would be best. Previously we discussed that the Windows dependencies stuff would remain on a Windows branch because it was diverging so much from the Linux/Mac stuff (separate scripts etc). Since then I've made some progress towards config-based rather than script-based builds, and @boberfly indicated that this might allow Windows to build with the same setup as Linux/Mac. Where is your latest work on that spectrum?

**Comment by ericmehl** [comment]
Sounds good, I'll open up a fresh PR in a minute. 

You'll see in the new PR I made some changes to your build script and all of the dependencies are building from the same code on Linux and Windows. Since we are using CMake throughout, the config scripts make heavy use of your platform specific override capability so it's essentially a parallel build, but at least all of the code lives together happily.

I'm not set up to build on Mac and didn't see anything for Travis so unfortunately I can't confirm they are working on Mac.

I'll include a summary of the status when I post the PR.

**Pull request closed without merging**
